const {chromium}=require('C:/Users/ztech.pk/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--enable-webgl','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1204,height:826},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())});await page.goto('http://127.0.0.1:3000',{waitUntil:'networkidle'});await page.waitForTimeout(700);console.log('state',await page.evaluate(()=>window.__site?.getState()));await page.screenshot({path:'reference/site-hero.png'});
for(const [id,p,name] of [['neural',0,'neural'],['programs',.5,'projects'],['updates',.12,'gallery'],['updates',.97,'build'],['prompts',0,'prompts'],['prompts',1,'outro']]){await page.evaluate(({id,p})=>{const e=document.getElementById(id);window.scrollTo(0,e.offsetTop+(e.offsetHeight-innerHeight)*p)},{id,p});await page.waitForTimeout(350);await page.screenshot({path:`reference/site-${name}.png`});}
await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('searchbox').fill('Nova');console.log('Search Nova',await page.locator('.search-results').innerText());await page.locator('.search-results button').click();console.log('Project dialog',await page.locator('#modal-title').innerText());await page.keyboard.press('Escape');console.log('Escape closes',await page.locator('dialog[open]').count()===0);
await page.getByRole('button',{name:'Get Started',exact:true}).first().click();await page.getByLabel('Your name').fill('Preview Test');await page.getByLabel('Email address').fill('preview-test@example.com');await page.locator('#join-form button').click();await page.waitForFunction(()=>document.querySelector('.form-status').textContent.includes('saved'));console.log('Signup',await page.locator('.form-status').innerText());await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:3000',{waitUntil:'networkidle'});await page.waitForTimeout(500);await page.screenshot({path:'reference/site-mobile.png'});console.log('mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await page.evaluate(()=>window.scrollTo(0,document.getElementById('neural').offsetTop));await page.waitForTimeout(250);await page.screenshot({path:'reference/site-mobile-neural.png'});console.log('errors',errors);await browser.close();
const file='data/join.jsonl';if(fs.existsSync(file)){const lines=fs.readFileSync(file,'utf8').split('\n').filter(Boolean).filter(x=>JSON.parse(x).email!=='preview-test@example.com');fs.writeFileSync(file,lines.map(x=>x+'\n').join(''));}if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
